# Generated by Django 3.0 on 2020-09-16 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('day05', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee2',
            options={'verbose_name': '员工', 'verbose_name_plural': '员工'},
        ),
    ]
